import { notifyUser } from './userFeedback';

export interface PrintField {
  label: string;
  value: string | number | null | undefined;
  wide?: boolean;
}

export interface PrintDocumentOptions {
  title: string;
  subtitle?: string;
  reference?: string;
  fields: PrintField[];
  footer?: string;
  language?: 'ar' | 'en';
}

const escapeHtml = (value: unknown) => String(value ?? '')
  .replace(/&/g, '&amp;')
  .replace(/</g, '&lt;')
  .replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;')
  .replace(/'/g, '&#039;');

export function printDocument(options: PrintDocumentOptions): boolean {
  const language = options.language || 'ar';
  const rtl = language === 'ar';
  const popup = window.open('', '_blank', 'width=900,height=720');
  if (!popup) {
    notifyUser({
      kind: 'warning',
      ar: 'تعذر فتح صفحة الطباعة. اسمح بالنوافذ المنبثقة لهذا الموقع ثم حاول مرة أخرى.',
      en: 'The print page could not be opened. Allow pop-ups for this site and try again.'
    });
    return false;
  }

  const rows = options.fields.map(field => `
    <div class="field ${field.wide ? 'wide' : ''}">
      <div class="label">${escapeHtml(field.label)}</div>
      <div class="value">${escapeHtml(field.value || '—')}</div>
    </div>`).join('');

  popup.document.open();
  popup.document.write(`<!doctype html>
<html lang="${language}" dir="${rtl ? 'rtl' : 'ltr'}">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>${escapeHtml(options.title)}</title>
<style>
  @page { size: A4; margin: 14mm; }
  * { box-sizing: border-box; }
  body { margin:0; background:#fff; color:#0f172a; font-family: Arial, Tahoma, sans-serif; }
  .page { max-width: 780px; margin: 0 auto; padding: 8px; }
  .header { border-bottom: 3px solid #29b4c4; padding-bottom: 14px; margin-bottom: 20px; display:flex; justify-content:space-between; gap:20px; align-items:flex-start; }
  .brand { font-size:12px; font-weight:700; color:#64748b; letter-spacing:.08em; }
  h1 { margin:4px 0 0; font-size:24px; }
  .subtitle { margin-top:6px; color:#64748b; font-size:12px; }
  .reference { border:1px solid #cbd5e1; background:#f8fafc; padding:9px 12px; border-radius:10px; font-size:12px; white-space:nowrap; }
  .grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:10px; }
  .field { border:1px solid #e2e8f0; border-radius:10px; padding:10px 12px; min-height:58px; }
  .field.wide { grid-column:1/-1; }
  .label { color:#64748b; font-size:10px; font-weight:700; margin-bottom:6px; }
  .value { color:#0f172a; font-size:13px; font-weight:700; white-space:pre-wrap; overflow-wrap:anywhere; }
  .footer { margin-top:28px; border-top:1px solid #e2e8f0; padding-top:12px; font-size:10px; color:#94a3b8; text-align:center; }
  .actions { display:flex; justify-content:center; gap:8px; margin-top:20px; }
  .actions button { border:0; border-radius:10px; padding:10px 18px; cursor:pointer; font-weight:700; }
  .print { background:#0f172a; color:#fff; }
  .close { background:#e2e8f0; color:#334155; }
  @media print { .actions { display:none !important; } .page { padding:0; } }
  @media (max-width:640px) { .grid { grid-template-columns:1fr; } .field.wide { grid-column:auto; } .header { flex-direction:column; } }
</style>
</head>
<body>
  <main class="page">
    <header class="header">
      <div>
        <div class="brand">AZHAR RESIDENCE</div>
        <h1>${escapeHtml(options.title)}</h1>
        ${options.subtitle ? `<div class="subtitle">${escapeHtml(options.subtitle)}</div>` : ''}
      </div>
      ${options.reference ? `<div class="reference">${escapeHtml(options.reference)}</div>` : ''}
    </header>
    <section class="grid">${rows}</section>
    <div class="footer">${escapeHtml(options.footer || (rtl ? 'تم إصدار هذا المستند من نظام إدارة مجمع أزهار.' : 'Generated by Azhar Residence Management System.'))}</div>
    <div class="actions">
      <button class="print" onclick="window.print()">${rtl ? 'طباعة' : 'Print'}</button>
      <button class="close" onclick="window.close()">${rtl ? 'إغلاق' : 'Close'}</button>
    </div>
  </main>
</body>
</html>`);
  popup.document.close();
  popup.focus();
  return true;
}

export interface PrintTableOptions {
  title: string;
  subtitle?: string;
  columns: { key: string; label: string }[];
  rows: Record<string, unknown>[];
  language?: 'ar' | 'en';
  footer?: string;
}

export function printTableDocument(options: PrintTableOptions): boolean {
  const language = options.language || 'ar';
  const rtl = language === 'ar';
  const popup = window.open('', '_blank', 'width=1100,height=760');
  if (!popup) {
    notifyUser({ kind: 'warning', ar: 'تعذر فتح تقرير الطباعة. اسمح بالنوافذ المنبثقة لهذا الموقع ثم حاول مرة أخرى.', en: 'The print report could not be opened. Allow pop-ups and try again.' });
    return false;
  }
  const head = options.columns.map(c => `<th>${escapeHtml(c.label)}</th>`).join('');
  const body = options.rows.length ? options.rows.map(row => `<tr>${options.columns.map(c => `<td>${escapeHtml(row[c.key] ?? '—')}</td>`).join('')}</tr>`).join('') : `<tr><td colspan="${options.columns.length}">${rtl ? 'لا توجد بيانات للطباعة' : 'No data to print'}</td></tr>`;
  popup.document.open();
  popup.document.write(`<!doctype html><html lang="${language}" dir="${rtl?'rtl':'ltr'}"><head><meta charset="utf-8"><title>${escapeHtml(options.title)}</title><style>
  @page{size:A4 landscape;margin:10mm}*{box-sizing:border-box}body{font-family:Arial,Tahoma,sans-serif;color:#0f172a;margin:0}.page{padding:4px}.top{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid #29b4c4;padding-bottom:12px;margin-bottom:14px}.brand{font-size:11px;color:#64748b;font-weight:700;letter-spacing:.08em}h1{font-size:22px;margin:4px 0}.sub{font-size:11px;color:#64748b}.date{font-size:10px;color:#64748b}table{width:100%;border-collapse:collapse;font-size:9px}th{background:#0f172a;color:#fff;padding:7px 5px;border:1px solid #334155}td{padding:6px 5px;border:1px solid #cbd5e1;vertical-align:top}tr:nth-child(even) td{background:#f8fafc}.footer{margin-top:12px;font-size:9px;color:#94a3b8;text-align:center}.actions{text-align:center;margin-top:14px}.actions button{border:0;border-radius:9px;padding:9px 16px;margin:0 4px;font-weight:700;cursor:pointer}.p{background:#0f172a;color:#fff}.c{background:#e2e8f0;color:#334155}@media print{.actions{display:none}}
  </style></head><body><main class="page"><div class="top"><div><div class="brand">AZHAR RESIDENCE</div><h1>${escapeHtml(options.title)}</h1>${options.subtitle?`<div class="sub">${escapeHtml(options.subtitle)}</div>`:''}</div><div class="date">${escapeHtml(new Date().toLocaleString(rtl?'ar-EG':'en-US'))}</div></div><table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table><div class="footer">${escapeHtml(options.footer || (rtl?'تم إصدار التقرير من نظام إدارة مجمع أزهار.':'Generated by Azhar Residence Management System.'))}</div><div class="actions"><button class="p" onclick="window.print()">${rtl?'طباعة / حفظ PDF':'Print / Save PDF'}</button><button class="c" onclick="window.close()">${rtl?'إغلاق':'Close'}</button></div></main></body></html>`);
  popup.document.close(); popup.focus(); return true;
}
